application:
  subdomain: astrbot
  background_task: true
  upstreams:
    - location: /
      backend: http://astrbot:6185/
  public_path:
    - /
services:
  astrbot:
    # soulter/astrbot:v4.25.5
    # upstream: docker.io/soulter/astrbot:v4.26.6
    image: registry.lazycat.cloud/czyt/soulter/astrbot:c31402826acab28b
    environment:
      - TZ=Asia/Shanghai
    binds:
      - /lzcapp/var/data:/AstrBot/data
