lzc-sdk-version: "0.1"
name: AstrBot
package: cloud.lazycat.app.astrbot
version: 3.4.30
description: 一个支持大语言模型（LLM）接入功能的聊天机器人及开发框架
homepage: https://github.com/Soulter/AstrBot
author: Soulter
application:
  subdomain: astrbot
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://astrbot.cloud.lazycat.app.astrbot.lzcapp:6185/
  public_path:
    - /

services:
  astrbot:
    image: registry.lazycat.cloud/czyt/soulter/astrbot:019142a954f3c984
    binds:
      - /lzcapp/var/data:/AstrBot/data
